Repository callstack/react-native-testing-library, pull requests merged in 2022-10, with the labels that each got.

#1175 docs: add typedefs for queries
  website/docs/Queries.md
Labels: docs

#1166 fix: *ByA11yState default value false value for busy, disabled & selected state
  src/helpers/accessiblity.ts
  src/helpers/matchers/accessibilityState.ts
  src/queries/__tests__/a11yState.test.tsx
  src/queries/a11yState.ts
  src/queries/role.ts
  website/docs/Queries.md
Labels: bug, a11y

#1177 fix: do not use a real timeout in waitfor when using fake timers
  src/__tests__/waitFor.test.tsx
  src/waitFor.ts
Labels: hacktoberfest-accepted

#1193 Add queryOptions to labelText and hintText
  src/matches.ts
  src/queries/__tests__/hintText.test.tsx
  src/queries/__tests__/labelText.test.tsx
  src/queries/hintText.ts
  src/queries/labelText.ts
  src/queries/makeQueries.ts
  typings/index.flow.js
  website/docs/Queries.md
Labels: hacktoberfest-accepted

#1204 chore: add codecov badge to README
  README.md
Labels: hacktoberfest-accepted
